### PR TITLE
Add some functions

### PR DESCRIPTION
**Pull request by shish**
Adding some functions that I need for https://github.com/shish/rosettaboy

For some reason my window isn't showing up at all which I still need to debug, but these specific functions appear to be working as intended :)

### CODE REVIEW

**Comment by shish** [comment]
Update: Window shows, I can create a Renderer backed by the Window, and drawing using that works... but when I create a SoftwareRenderer backed by a Surface, draw to that, and blit the results to the screen (as is the recommended approach for doing pixel-level work with decent performance), it shows up corrupt :( The same thing works fine in other languages, so I wonder if I've messed up the PHP-to-native translation layer somehow... A second pair of eyes to check if these functions are implemented right would be appreciated ^^

**Review by santiagolizardo — APPROVED** [review]

**Comment by santiagolizardo** [comment]
Thanks for your contribution @shish !
_The code seems to work on my machine (TM)._
Do you have a snippet of code I could try that make use of the troublesome function? Thanks

**Comment by shish** [comment]
I haven't got a _minimal_ repro right now, but I'm using this in https://github.com/shish/rosettaboy - where you _should_ be able to
```
git clone https://github.com/shish/rosettaboy
cd rosettaboy/php
wget https://github.com/sjl/cl-gameboy/blob/master/roms/opus5.gb?raw=true
./build.sh
./rosettaboy-release opus5.gb
```

(I am willing to try building a smaller use-case to try and recreate the problem in a minimal way, but it'll need to wait until after my christmas travels are finished :) )

**Comment by santiagolizardo** [comment]
Hey @shish ; Glad to confirm that this now works!
image
Unfortunately the performance of the PHP emulation is terrible compared to the C++ one and I don't think is down to the language. I'll have a look at the code a bit closer in the next few days to see if I can spot any optimisations on either the SDL extension or the RosettaBoy sides :)

**Pull request merged**
