### PR TITLE
Add PHP 8 support

### PR DESCRIPTION
**Pull request by kea**
Tests are green for both PHP 7 and 8 but please, review the PR carefully. ;)
It left to fix some warning with `php_error_docref` `%ld` vs `%lld`.

### CODE REVIEW

**Comment by santiagolizardo** [comment]
@kea what are your thoughts on removing PHP7 support? It's only going to be actively supported for 5 more months[1]. Personally I would remove all the PHP7 support and focus on a great PHP8 experience, but I am curious to know your thoughts.

[1] https://www.php.net/supported-versions.php

**Comment by kea** [comment]
I don't have a strong opinion about removing PHP7 support. I've only seen other extensions maintain both, and I followed that path. But if you want to stay with the 2.3.x for PHP 7 and release the 2.4.x for PHP 8 with stub and other improvements, I think it should be easy to maintain.

**Review by santiagolizardo — APPROVED** [review]
Great work @kea . I have compiled this locally against 8.0.7 and works fine. Tests pass and the example scripts run as well.

**Comment by santiagolizardo** [comment]
That's shipped 🚀  http://pecl.php.net/package-info.php?package=sdl&version=2.5.0

**Pull request merged**
